feat: update mongodb version and related files
Teknodev/spica pull request #15
Opened 2024-09-12 14:36 UTC by mayroyo

2024-09-12 15:01 UTC, htuna07 requested changes
It seems fine except the change requests I added. Also it would be great if you execute the "yarn code:format"

2024-09-17 15:25 UTC, htuna07 commented on package.json
> +    "mongodb": "6.8.1",
why did we use static versions of mongodb and memory server instead of getting latest patches or minor updates?

2024-09-17 15:28 UTC, mavliut-fozliev commented on package.json
> +    "mongodb": "6.8.1",
fixed

2024-09-18 07:18 UTC, htuna07 approved these changes

2024-09-18 07:19 UTC, merged